### ISSUE TITLE
Worklist - QoL Feedback

### ISSUE THREAD

**Issue by Karelger** [computationalpathologygroup/ASAP#100]
**User Story**
Loading thumbnails from shares can take a while, without the user being able to tell when this process has finished.

**Requirements**
- Ensure a user is aware when all thumbnails have been loaded
- Allow a user to open a file, regardless of whether or not the thumbnail has been generated

**Tasks**
- [x] Improve thumbnail generation feedback
  - [x] Update status bar with "x out y thumbnails loaded"
  - [x] Create initial list of items that have their icons updated later on
  - [x] Either mark invalid files as invalid or if fast enough, validate on initial list creation

**Optional**
- Enable image opening on enter keystroke
- Allow a ASAP shortcut to switch to the next or previous image

**Comment by Karelger** [comment]
Checking whether or not a file is invalid takes too long from a single thread. This means it either needs to become a parallel process, or simply required rendering all the images, and then eliminating or marking invalid ones later on.

**Comment by Karelger** [comment]
Async updating of the statusbar seems to be causing issues, likely requires access restrictions

**Comment by Karelger** [comment]
Qt doesn't like updating the GUI from an async thread. Issue found, solving it

**Comment by Karelger** [comment]
Added shortcuts for switching between images while on the viewer tab, and enabled the enter key for selecting images on the worklist view
