### ISSUE TITLE
Prototype worklists

### ISSUE THREAD

**Issue by jmsmkn** [computationalpathologygroup/ASAP#91]
**User Story**
The user has a worklist, this contains a list of images that they need to open with ASAP. The worklist is defined by someone else. The software needs to get the worklist for this user, and then open each image. 

**Requirements**
- Worklists need to be stored in a database with relations to images which are also indexed in the database
- The worklists need to be downloadable from the database (eg, via a REST API)
- The images which are located either on the local disc or on the network are made available
- ASAP must be able to query the worklist and images
- ASAP must be able to download and view images that are served

**Tasks**
- [x] Push current prototype to new branch
- [x] Create the tables within ASAP by getting the schema from the API, see: http://www.django-rest-framework.org/api-guide/schemas/
- [x] Connect the worklist gui to the ASAP gui so that the images can be viewed
  - [x] Work out how to pass a file to ASAP
  - [x] Integrate GUI elements to fit 1 screen
  - [x] Pass a worklist element from the worklist GUI to the ASAP GUI

**Out of scope**
- Image thumbnail generation and display
- Worklist creation
- Non local image serving (eg, images in girder)

**Comment by Karelger** [comment]
Weak integration in the form of two seperate windows has been achieved. Using this as a demo, it was decided to integrate the both GUI's into a single window where a tab element decides whether the viewer is displayed, or the worklist interface.

**Comment by Karelger** [comment]
Integrated the worklist and viewer into a single window. A Tab widget allows for switching between the two windows, and the composite window that serves as parent allows for additional views or options to be added.
