### ISSUE TITLE
Worklist Feature Expansion - 1

### ISSUE THREAD

**Issue by Karelger** [computationalpathologygroup/ASAP#95]
**User Story**
The user wishes to select images from a directory or file list, or worklists from an alternate source (with a supported format). This source needs to be stored in a file, so it can be reused on startup.

**Requirements**
- A settings file that stores the source information
- A GUI element that can edit this settings file
- A way to consume alternate sources, which may have a reduced set of tables
- The ability to display these alternate sources without any redundant views

**Tasks**
- [x] Settings file
  - [x] Create INI file parser
  - [x] Create GUI element to set INI file parameters
- [x] Alternate sources
  - [x] Refactor abstract interface to adhere to current async methods
  - [x] Implement the ability to recognize which views are required to accurately display the source
  - [x] Implement automatic GUI adjustments, according to the source
  - [x] Load preferred source according to settings file
  - [x] Implement directories as alternate source

**Optional**
- Add async thumbnail generation for acquired files
- Add filelist as alternate source
