### ISSUE TITLE
Worklist Feature Refinement

### ISSUE THREAD

**Issue by Karelger** [computationalpathologygroup/ASAP#96]
**User Story**
The current Worklist interface offers all features required to use data sources to browse through available images and related information. But in its current state, the interface is unwieldly to use due to slight differences in views or the ability to edit fields that should remain constant.

**Tasks**
- [x] Refine GUI views
  - [x] Remove unwanted interactions
  - [x] Split source access into local and external screens
  - [x] Add thumbnail generation for WSIs
- [x] Refine Data Source access
  - [x] Add sanitization checks
  - [x] Add file list as potential source 

**Optional**
- Merge menu bars for the imported views
- Allow the composed window to disable elements within the ASAP GUI
