### ISSUE TITLE
Worklist - Feature Refinement 2

### ISSUE THREAD

**Issue by Karelger** [computationalpathologygroup/ASAP#98]
**User Story**
The user currently pulls all available worklists from the Django instance without the need for a login or an account. The desired behaviour is that each user has an account that requires authorization before they're able to access their personalized worklists. 

Sources require a fair amount of interaction to switch. Adding the ability to quickly select previously used sources can reduce the overhead required for a user. Additionally, feedback to the user can be improved by adding UI messages and switching context once an item is selected. This can be combined with removing some UI spacing issues and improving the position of the menu bar to retain a clean look.

**Required**
- Removing of wasted whitespace
- Merging of redundant elements
- Adding more reactive components based on user actions
- Storing previously used sources to the extent of 5 maximum
- Enabling the Django data access to handle tokens and authentication
- Improving the External Source screen to align with the Django access

**Tasks**
- [x] UI Refinement
  - [x] Remove composite window padding
  - [x] Enable context switching on image selection
  - [x] Add last five previous sources as quick selection
  - [x] Merge menu bars
  - [x] Add status messages to Worklist status bar
- [x] Setup Django authentication and permissions
  - [x] Setup Django authentications
  - [x] Setup Django permissions
  - [ ] Implement authentication for worklist data access
  - [ ] Implement a proper login for the External Source selection
- [x] Create CMakefile for the Worklist project

**Optional**
- Fix async thumbnail loading
- Fix static thumbnail sizes
- Add favourite sources

**Comment by Karelger** [comment]
Enabled async thumbnail generation, sadly the view is getting updated through a hack for now.

**Comment by Karelger** [comment]
Added Django support in: https://github.com/comic/grand-challenge.org/projects/3

Will add new ticket for implementing Cmakefile
