### ISSUE TITLE
Worklist - Thumbnail Display

### ISSUE THREAD

**Issue by Karelger** [computationalpathologygroup/ASAP#99]
**User Story**
Files are currently displayed whenever they have the correct extension, even if ASAP is unable to generate a thumbnail for them. These thumbnails still vary in size and create a messy look.

**Requirements**
- Ensure only readable files are displayed within the interface
  - Ensure that files readable, but without level aren't discarded
- Ensure all file icons are always of the same size

**Tasks**
- [x] Available images display
  - [x] Don't display files that are completely unreadable by ASAP
  - [x] Confirm that files without levels aren't being handled incorrectly by the icon generator
- [x] Thumbnail size
  - [x] Change scaling so that the largest dimension is rescaled into the correct format,
  - [x] Add padding to the lower dimension to adhere to the correct format
  - [x] Ensure the thumbnail is centered within its icon
